### ISSUE TITLE
SoundCloud login needs to be implemented

### ISSUE THREAD

**Issue by kristiehoward** [zgleicher/DJ-LEVels#3]
[x] user can login with soundcloud credentials
[x] user who logins in is added to DB of users (@sam-jay can help)
[ ] user can be added in Contributors or Followers to an existing group (@kbh2120 to check)

**Comment by zgleicher** [comment]
@sam-jay: server/auth/soundcloud/index.js has a TODO to put user in database if does not exist. User object in callback is documented here https://developers.soundcloud.com/docs/api/reference#users.

**Comment by zgleicher** [comment]
@kbh2120 Need to use isAuthenticated() to determine what should and should not be shown to an authenticated user. Currently I put a toggling login and logout in the navbar. I think this should be updated so that if a user is not logged in, he or she should be presented a view with a large button in the center that says Login with SoundCloud. Once Logged in, we can use isAuthenticated() to show the main app. This is the splash page in issue 4. I can work on this now.

**Comment by zgleicher** [comment]
Once these are finished I will scrap all the crappy original login functionality

**Comment by zgleicher** [comment]
@kbh2120 @sam-jay I am going to work on completing all the auth stuff
